#!/bin/bash

# Parse argument
# Ensure single argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <interval_in_minutes>"
    exit 1
fi

# Ensure argument is positive integer
INTERVAL="$1"
if ! [[ "$INTERVAL" =~ ^[0-9]+$ ]] || [ "$INTERVAL" -le 0 ]; then
    echo "Error: Interval must be a positive integer."
    exit 1
fi

# Schedule job
ROOT_DIR="$(readlink -f $(dirname $(dirname "$BASH_SOURCE[0]}")))"
CRON_JOB="*/$INTERVAL * * * * $ROOT_DIR/scripts/invoke_weather_report.sh"

# Check if cron job already exists
# 2>/dev/null prevents any errors generated by crontab -l from being searched by grep
# If grep cannot find the cron job, it returns an error status (1 != 0) so the "if" evaluates to false
if crontab -l 2>/dev/null | grep -F "$CRON_JOB" >/dev/null; then
    echo "Cron job already exists."
# If it doesn't exist, get a list of all existing cron jobs (discarding errors), add the new cronjob to the end, and send to crontab
else
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    echo "Cron job added: $CRON_JOB"
fi